config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords'}
  resources :job_titles, :allowance_types, :vacation_types, :roles, :attachment_types, :roles, :branches, :companies

  resources :currencies do
    collection do
      get 'default'
    end
    member do
      post 'default' => 'currencies#set_default'
    end
  end

  resources :leave_applications, except: [:edit, :update, :destroy] do
    member do
      post 'approve'
      post 'deny'
    end
  end

  resources :departments do
    member do
      get 'job_titles'
    end
  end

  resources :employees do
    collection do
      get 'download_pdf' => 'employees#download_pdf'
    end
    member do
      get 'download_attachment/:attachment_id' => 'employees#download_attachment',
        as: :attachment
    end
  end

  resources :users, only: [:edit, :new, :create, :index, :destroy, :show, :update] do
    member do
      get 'change_password' => 'users#change_password'
      post 'terminate'      => 'users#terminate'
      post 'unterminate'    => 'users#unterminate'
    end
    collection do
      patch 'update_password'
      get   'check_uniqueness'
    end
  end

  resources :notifications, only: [:index] do
    member do
      post 'mark_as_read'
    end
  end

  resources :journal_entry_sessions, only: [:create] do
    resources :journal_entries, only: [:index, :create, :update, :destroy, :show]
  end

  resources :journal_entries, only: [:index] do
    collection do
      get :build_options
    end
  end

  delete 'journal_entry_sessions/:id/close' => 'journal_entry_sessions#close', as: :close_journal_entry_session

  resources :account_main_types, path: "account_headers", only: [:show, :edit, :update, :index] do
    member do
      get 'account_sub_headers'
    end
  end

  resources :accounts do
    collection do
      get 'view'          => 'accounts#view'
      get 'account_tree'  => 'accounts#account_tree'
      get 'balance_sheet' => 'accounts#balance_sheet'
    end
  end

  resources :account_sub_types, path: 'account_sub_headers' do
    member do
      get 'account_lists'
    end
  end

  resources :account_types, path: 'account_lists'
  get 'profile' => 'users#profile'
  patch 'update_profile' => 'users#update_profile'

  resources :dynamic_menus do
    collection do
      get 'to_account_type_ids/:from_account_type_ids' => 'dynamic_menus#to_account_type_ids'
      get 'check_uniqueness_for_name'
    end
    resources :transactions
  end

  get 'shift_summary' => 'transactions#shift_summary'
end

app/views/branches/_form.html.haml
= form_for branch, html: { class: "form-horizontal" } do |f|
  = render "shared/errors", resource: branch
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .hr-line-dashed
  .form-group
    = f.label :adderss, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :address, class: 'form-control'
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, class: 'form-control'
  .form-group
    .col-sm-4.col-sm-offset-2
      = f.submit "Save", class: "btn btn-primary"
      = link_to "Cancel", branches_path, class: "btn btn-primary"

app/views/branches/destroy.js.erb
$("[data-id=<%= @branch.id %>]").remove();
$(".wrapper-content").prepend("<%= j render "shared/flash_messages" %>");

app/views/branches/edit.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :index, Branch
        = link_to "All Branches", branches_path, class: "btn btn-primary btn-rounded m-sm"
      .ibox.float-e-margins
        .ibox-title
          %h5 Edit a Branch
        .ibox-content
          = render 'form', branch: @branch

app/views/branches/index.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :new, Branch
        = link_to new_branch_path, class: "btn btn-primary btn-rounded m-sm pull-right" do
          %i.fa.fa-plus{"aria-hidden" => true}
          &nbsp;&nbsp; New Branch
      .ibox.float-e-margins
        .ibox-title All Branches
        .ibox-content
          .table-responsive
            %table.table.table-bordered.table-striped
              %thead
                %tr
                  - if can? :show, Branch
                    %th ID
                  %th Name
                  %th Address
                  %th Description
                  - if can?(:edit, Branch) || can?(:destroy, Branch)
                    %th Actions
              %tbody
                - @branches.each do |branch|
                  %tr{data: { id: branch.id } }
                    - if can? :show, Branch
                      %td.font-bold= link_to branch.id, branch
                    %td= branch.name
                    %td= branch.address
                    %td= branch.description
                    - if can?(:edit, Branch) || can?(:destroy, Branch)
                      %td
                        - if can? :delete, Branch
                          = link_to branch, method: :delete, remote: true, data: { confirm: "Are you sure to delete this branch from database?" }, class: "action-link" do
                            %i.fa.fa-trash{"aria-hidden" => true}
                        - if can? :edit, Branch
                          = link_to edit_branch_path(branch), class: "action-link" do
                            %i.fa.fa-pencil{"aria-hidden" => true}

app/views/branches/new.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :index, Branch
        = link_to "All Branches", branches_path, class: "btn btn-primary btn-rounded m-sm"
      .ibox.float-e-margins
        .ibox-title
          %h5 Create a new Branch
        .ibox-content
          = render 'form', branch: @branch

app/views/branches/show.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-title
          %h2= @branch.name
        .ibox-content
          .col-md-2
            %p.font-bold Name
          .col-md-10
            %p.font-bold= @branch.name
          %br
          .col-md-2
            %p.font-bold Address
          .col-md-10
            %p= @branch.address
          %br
          .col-md-2
            %p.font-bold Description
          .col-md-10
            %p= @branch.description
          %br
          .clearfix
  .row
    .col-lg-12
      - if can? :edit, Branch
        = link_to "Edit", edit_branch_path(@branch), class: "btn btn-primary btn-rounded"
      - if can? :index, Branch
        = link_to "All Branches", branches_path, class: "btn btn-primary btn-rounded"