config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords'}
  resources :job_titles, :allowance_types, :vacation_types, :roles, :attachment_types, :roles, :branches, :companies

  resources :currencies do
    collection do
      get 'default'
    end
    member do
      post 'default' => 'currencies#set_default'
    end
  end

  resources :leave_applications, except: [:edit, :update, :destroy] do
    member do
      post 'approve'
      post 'deny'
    end
  end

  resources :departments do
    member do
      get 'job_titles'
    end
  end

  resources :employees do
    collection do
      get 'download_pdf' => 'employees#download_pdf'
    end
    member do
      get 'download_attachment/:attachment_id' => 'employees#download_attachment',
        as: :attachment
    end
  end

  resources :users, only: [:edit, :new, :create, :index, :destroy, :show, :update] do
    member do
      get 'change_password' => 'users#change_password'
      post 'terminate'      => 'users#terminate'
      post 'unterminate'    => 'users#unterminate'
    end
    collection do
      patch 'update_password'
      get   'check_uniqueness'
    end
  end

  resources :notifications, only: [:index] do
    member do
      post 'mark_as_read'
    end
  end

  resources :journal_entry_sessions, only: [:create] do
    resources :journal_entries, only: [:index, :create, :update, :destroy, :show]
  end

  resources :journal_entries, only: [:index] do
    collection do
      get :build_options
    end
  end

  delete 'journal_entry_sessions/:id/close' => 'journal_entry_sessions#close', as: :close_journal_entry_session

  resources :account_main_types, path: "account_headers", only: [:show, :edit, :update, :index] do
    member do
      get 'account_sub_headers'
    end
  end

  resources :accounts do
    collection do
      get 'view'          => 'accounts#view'
      get 'account_tree'  => 'accounts#account_tree'
      get 'balance_sheet' => 'accounts#balance_sheet'
    end
  end

  resources :account_sub_types, path: 'account_sub_headers' do
    member do
      get 'account_lists'
    end
  end

  resources :account_types, path: 'account_lists'
  get 'profile' => 'users#profile'
  patch 'update_profile' => 'users#update_profile'

  resources :dynamic_menus do
    collection do
      get 'to_account_type_ids/:from_account_type_ids' => 'dynamic_menus#to_account_type_ids'
      get 'check_uniqueness_for_name'
    end
    resources :transactions
  end

  get 'shift_summary' => 'transactions#shift_summary'
end

app/models/employee.rb
class Employee < ApplicationRecord

  has_many :users
  has_many :vacations
  has_many :attachments, as: :attachable
  has_one :profile_image, -> { profile_image }, class_name: :Attachment, as: :attachable

  validates_associated :vacations, :attachments
  validates :first_name, :last_name, presence: true
  validate :attachment_types_should_be_unique

  NATIONALITIES = ["Sri Lanka", "India", "Nepal", "Phillippines"]
  accepts_nested_attributes_for :vacations,
                                allow_destroy: true,
                                reject_if: proc { |attributes|
                                  attributes['starts_from'].blank? ||
                                    attributes['ends_at'].blank?
                                }
  accepts_nested_attributes_for :attachments,
                                allow_destroy: true,
                                reject_if: proc { |attributes|
                                  attributes['image'].blank?
                                }


  def full_name
    [first_name, last_name]*" "
  end

  %w(passport_expiry visa_expiry medical_expiry appointment_date).each do |attribute|
    define_method "#{attribute}=" do |val|
      date = Date.strptime(val, "%d/%m/%Y") if val.present?
      write_attribute attribute.to_sym, date
    end
  end

  def department_name
    job_title.try(:department).try(:name)
  end

  def unallocted_attachment_type_ids
    allocated_ids = attachments.map(&:attachment_type_id)
    AttachmentType.ids - allocated_ids
  end

  def attachment_types_should_be_unique
     allocated_ids = attachments.map(&:attachment_type_id)
     unless allocated_ids.uniq.length == allocated_ids.length
       errors.add :base, "You can't upload an item for the same attachment type twice."
     end
  end

  def self.get_pdf_report(sort_column, sort_direction)
    self.includes(:profile_image, :vacations)
        .order(sort_column + " " + sort_direction)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource except: [:index]

  before_action :set_employee, only: [:edit, :update, :show, :destroy, :download_attachment]
  helper_method :sort_column

  def new
    @employee = Employee.new
    set_vacation
    set_attachment
    set_attachment_types
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee, notice: "Employee has successfully been saved."
    else
      render :new
    end
  end

  def edit
    set_attachment
    set_attachment_types
  end

  def update
    if @employee.update_attributes(employee_params)
      redirect_to @employee, notice: "Employee has successfully been updated."
    else
      render :edit
    end
  end

  def show
  end

  def index
    @employees = Employee.includes(:profile_image).order(sort_column + " " + sort_direction)
  end

  def destroy
    @employee && @employee.destroy    
    respond_to do |format|
      flash.now[:notice] = "Employee: #{@employee.full_name} has been deleted." 
      format.js
    end
  end

  def download_attachment
    attachment = @employee.attachments.find_by_id params[:attachment_id]
    if attachment
      data = open(attachment.image.url)
      send_data data.read, type: attachment.image_content_type, x_sendfile: true,
        url_based_filename: true, disposition: "attachment"
    else
    end
  end

  def download_pdf
    @employees = Employee.get_pdf_report(sort_column, sort_direction)
    respond_to do |format|
      format.pdf do
        pdf = EmployeePdf.new(@employees)
        send_data pdf.render, filename: "all_employees", type: "application/pdf"
      end
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :address, :phone_number, :passport_no, :passport_expiry, :nationality, :visa_no, :id_no, :visa_expiry, :medical_expiry, :date_of_joining, :appointment_date, attachments_attributes: [:id, :attachment_type_id, :image, :_destroy], vacations_attributes: [:id, :vacation_type_id, :starts_from, :ends_at, :_destroy])
  end

  def set_employee
    @employee = Employee.find(params[:id]) 
  end

  def set_vacation
    @employee.vacations.build
  end

  def set_attachment
    @employee.attachments.build
  end

  def set_attachment_types
    unallocated_ids = @employee.unallocted_attachment_type_ids
    @attachment_type_names_and_ids = AttachmentType.find(unallocated_ids).pluck(:name, :id)
  end

  def sort_column
    Employee.column_names.include?(params[:sort])? params[:sort] : "id"
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_allowance.html.haml
.row.m-t-xs.form-inline.m-l-xs
  = f.label :allowance_type_id, 'Allowance Type', class: 'control-label'
  = f.select :allowance_type_id, options_for_select(AllowanceType.all.map { |a| [a.name, a.id] }, selected: f.object.allowance_type_id), {}, class: 'form-control input-sm'
  .input-group.date
    %span.input-group-addon
      %i.fa.fa-calendar
    = f.text_field :starts_from, class: 'form-control allowance-start input-group date', placeholder: 'Starts from'
  .input-group.date
    %span.input-group-addon
      %i.fa.fa-calendar
    = f.text_field :ends_at, class: 'form-control allowance-end input-group date', placeholder: 'Ends at'

  = f.link_to_remove 'Remove', class: 'btn btn-outline btn-danger btn-xs m-l-sm m-t-sm'

app/views/employees/_attachment.html.haml
.row.form-inline
  = f.label :attachment_type_id, 'Attachment Type'
  - if f.object.attachment_type_id.is_a? Integer
    .attachment-type
      = f.select :attachment_type_id, options_for_select(AttachmentType.pluck(:name, :id), selected: f.object.attachment_type_id), {}, class: 'form-control input', disabled: true
  - elsif @attachment_type_ids.blank?
    .attachment-type
      = f.select :attachment_type_id, options_for_select(AttachmentType.pluck(:name, :id)), {}, class: 'form-control input'
  - else
    .attachment-type
      = f.select :attachment_type_id, options_for_select(@attachment_type_names_and_ids), {}, class: 'form-control input'
  - if f.object.image?
    .fileinput.fileinput-exists{ data: { provides: "fileinput" } }
      %span.btn.btn-default.btn-file
        %span.fileinput-new Select File
        %span.fileinput-exists Change
        = f.file_field :image, class: 'form-control'
      %span.fileinput-filename= f.object.image_file_name
  - else
    .fileinput.fileinput-new{ data: { provides: "fileinput" } }
      %span.btn.btn-default.btn-file
        %span.fileinput-new Select File
        %span.fileinput-exists Change
        = f.file_field :image, class: 'form-control'
      %span.fileinput-filename
  = f.link_to_remove 'Remove', class: 'btn btn-outline btn-danger btn-xs m-l-sm m-t-sm'

app/views/employees/_form.html.haml
= nested_form_for @employee, html: { class: "form-horizontal", id: "manageEmployee" } do |f|
  = render "shared/errors", resource: @employee
  %h3 Basic Info
  .form-group
    = f.label :first_name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :first_name, class: 'form-control'
  .hr-line-dashed
  .form-group
    = f.label :last_name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :last_name, class: 'form-control'
  .hr-line-dashed
  .form-group
    = f.label :email, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.email_field :email, class: 'form-control'
  .hr-line-dashed
  .form-group
    = f.label :phone_number, 'Mobile No.', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.phone_field :phone_number, class: 'form-control', data: { mask: "9999999999" }
  .hr-line-dashed
  .form-group
    = f.label :address, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :address, class: 'form-control'
  .hr-line-dashed
  %h3 Employment Info
  .form-group
    = f.label :nationality, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.select :nationality, Employee::NATIONALITIES, { selected: @employee.nationality, prompt: "Please choose nationality." }, class: 'form-control'
  .hr-line-dashed
  .form-group
    = f.label :passport_no, 'Passport No.', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :passport_no, class: 'form-control'
  .hr-line-dashed
  .form-group
    = f.label :passport_expiry, 'Passport Expiry', class: 'col-sm-2 control-label'
    .col-sm-2.input-group.date.m-r-md
      %span.input-group-addon
        %i.fa.fa-calendar
      = f.text_field :passport_expiry, class: 'form-control input-group date', id: "passportExpiry"
    .date-error
      = label_tag :passportExpiry, '', class: 'error', id: 'passportExpiry-error'
  .hr-line-dashed
  .form-group
    = f.label :visa_no, 'Visa No.', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :visa_no, class: 'form-control', data: { mask: "999999999999" }
  .hr-line-dashed
  .form-group
    = f.label :id_no, 'ID No.', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :id_no, class: 'form-control', data: { mask: "99999999999" }
  .hr-line-dashed
  .form-group
    = f.label :visa_expirty, 'Visa Expiry', class: 'col-sm-2 control-label'
    .col-sm-2.input-group.date.m-r-md
      %span.input-group-addon
        %i.fa.fa-calendar
      = f.text_field :visa_expiry, class: 'form-control input-group date', id: "visaExpiry"
    .date-error
      = label_tag :visaExpiry, '', class: 'error', id: 'visaExpiry-error'
  .hr-line-dashed
  .form-group
    = f.label :medical_expiry, 'Medical Expiry', class: 'col-sm-2 control-label'
    .col-sm-2.input-group.date.m-r-md
      %span.input-group-addon
        %i.fa.fa-calendar
      = f.text_field :medical_expiry, class: 'form-control input-group date', id: "medicalExpiry"
    .date-error
      = label_tag :medicalExpiry, '', class: 'error', id: 'medicalExpiry-error'
  .hr-line-dashed
  .form-group
    = f.label :appointment_date, 'Medical appointment date', class: 'col-sm-2 control-label'
    .col-sm-2.input-group.date.m-r-md
      %span.input-group-addon
        %i.fa.fa-calendar
      = f.text_field :appointment_date, class: 'form-control input-group date', id: "appointmentDate"
    .date-error
      = label_tag :appointmentDate, '', class: 'error', id: 'appointmentDate-error'
  .hr-line-dashed
  .form-group
    = label_tag :vacations, "Vacations", class: 'col-sm-2 control-label'
    .col-sm-10
      = f.fields_for :vacations do |vacation_field|
        = render 'vacation', f: vacation_field
      = f.link_to_add :vacations, class: 'btn btn-primary m-t-xs' do
        %i.fa.fa-plus-circle
        %span.bold Add a new Vacation
  .hr-line-dashed
  .form-group
    = label_tag :attachments, "Attachments", class: 'col-sm-2 control-label'
    .col-sm-10
      = f.fields_for :attachments do |attachment_field|
        = render 'attachment', f: attachment_field
      = f.link_to_add :attachments, class: 'btn btn-primary m-t-xs' do
        %i.fa.fa-plus-circle
        %span.bold Add a new attachment
  .hr-line-dashed
  .hr-line-dased
  .form-group
    .col-sm-4.col-sm-offset-2
      = f.submit "Save", class: "btn btn-primary"
      = link_to "Cancel", employees_path, class: "btn btn-primary"

app/views/employees/_vacation.html.haml
.row.form-inline
  = f.label :vacation_type_id, 'Vacation Type'
  = f.select :vacation_type_id, options_for_select(VacationType.all.map { |v| [v.name, v.id] }, selected: f.object.vacation_type_id), {}, class: 'form-control input-sm'
  .input-group.date.vacation-dates
    %span.input-group-addon
      %i.fa.fa-calendar
    = f.text_field :starts_from, class: 'form-control input-group date', placeholder: 'Starts from'
  .input-group.date.vacation-dates
    %span.input-group-addon
      %i.fa.fa-calendar
    = f.text_field :ends_at, class: 'form-control input-group date', placeholder: 'Ends at'
  = f.link_to_remove 'Remove', class: 'btn btn-outline btn-danger btn-xs m-l-sm m-t-sm'

app/views/employees/destroy.js.erb
$("[data-id=<%= @employee.id %>]").remove();
$(".wrapper-content").prepend("<%= j render "shared/flash_messages" %>");

app/views/employees/edit.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :index, Employee
        = link_to "All Employees", employees_path, class: "btn btn-primary btn-rounded m-sm"
      .ibox.float-e-margins
        .ibox-title
          %h5 Edit an Employee
        .ibox-content
          = render 'form'

app/views/employees/index.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :new, Employee
        = link_to new_employee_path, class: "btn btn-primary btn-rounded m-sm pull-right" do
          %i.fa.fa-plus{"aria-hidden" => true}
          &nbsp;&nbsp; New Employee
        - if can? :download_pdf, Employee
          = form_tag download_pdf_employees_path, method: "get", id: "pdfForm" do
            = hidden_field_tag :format, 'pdf'
            = submit_tag 'Download PDF', class: "btn btn-primary btn-rounded m-sm pull-right", id: "pdfDownload"
      .ibox.float-e-margins
        .ibox-title.p-sm
          .form-group.pull-right.m-t-n-xs
            = text_field_tag :search, nil, class: "form-control", id: "searchEmployees"
          .pull-right.m-r-md.m-t-xxs
            = label_tag :search
        .ibox-content
          .table-responsive
            %table.table.table-bordered.table-striped.pretty.employeeTable
              %thead
                %tr 
                  - if can? :show, Employee
                    %th= sortable "id", "ID"
                  %th Profile Picture
                  %th= sortable "first_name"
                  %th= sortable "last_name"
                  %th= sortable "phone_number"
                  %th= sortable "visa_expiry"
                  %th= sortable "medical_expiry"
                  %th= sortable "passport_expiry"
                  - if can?(:edit, Employee) || can?(:destroy, Employee)
                    %th Actions
              %tbody
                - @employees.each do |employee|
                  %tr.employees
                    - if can? :show, Employee
                      %td= link_to employee.id, employee
                    - if employee.profile_image
                      %td= image_tag employee.profile_image.image.url(:thumb)
                    - else
                      %td No image
                    %td.first-name= employee.first_name
                    %td.last-name= employee.last_name
                    %td= employee.phone_number
                    %td= employee.visa_expiry.try(:strftime, "%b %d, %Y")
                    %td= employee.medical_expiry.try(:strftime, "%b %d, %Y")
                    %td= employee.passport_expiry.try(:strftime, "%b %d, %Y")
                    - if can?(:edit, Employee) || can?(:destroy, Employee)
                      %td
                        - if can? :destroy, Employee
                          = link_to employee, method: :delete, remote: true, data: { confirm: "Are you sure to delete this employee from database?" }, class: "action-link" do
                            %i.fa.fa-trash{"aria-hidden" => true}
                        - if can? :edit, Employee
                          = link_to edit_employee_path(employee), class: "action-link" do
                            %i.fa.fa-pencil{"aria-hidden" => true}
          .row
            .col-lg-12
              %span
                Total Employees: 
              %span#totalEmployees

app/views/employees/new.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :index, Employee
        = link_to "All Employees", employees_path, class: "btn btn-primary btn-rounded m-sm"
      .ibox.float-e-margins
        .ibox-title
          %h5 Create a new Employee
        .ibox-content
          = render 'form'

app/views/employees/show.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-title
          %h2=@employee.full_name
        .ibox-content
          .row
            .col-md-2 
              %p.font-bold First Name
            .col-md-10
              %p= @employee.first_name
          .row
            .col-md-2
              %p.font-bold Last Name
            .col-md-10
              %p= @employee.last_name
          .row
            .col-md-2
              %p.font-bold Address
            .col-md-10
              %p= @employee.address
          .row
            .col-md-2
              %p.font-bold Email
            .col-md-10
              %p= @employee.email
          .row
            .col-md-2
              %p.font-bold Phone number
            .col-md-10
              %p= @employee.phone_number
          .row
            .col-md-2
              %p.font-bold Nationality
            .col-md-10
              %p= @employee.nationality
          .row
            .col-md-2
              %p.font-bold Passport No.
            .col-md-10
              %p= @employee.passport_no
          .row
            .col-md-2
              %p.font-bold Passport Expiry
            .col-md-10
              %p= @employee.passport_expiry.try(:strftime, "%b %d, %Y")

          .row
            .col-md-2
              %p.font-bold Visa No.
            .col-md-10
              %p= @employee.visa_no
          .row
            .col-md-2
              %p.font-bold Visa Expiry
            .col-md-10
              %p= @employee.visa_expiry.try(:strftime, "%b %d, %Y")
          .row
            .col-md-2
              %p.font-bold Attachments
            .col-md-10
              .row
              - if @employee.attachments.blank?
                %p There are currently no attachments.
              -else
                .col-md-3.font-bold Attachment Type
                .col-md-3.font-bold Attachment Name
                .col-md-3.font-bold Attachment Thumbnail
                .col-md-3.font-bold Download
                - @employee.attachments.each do |attachment|
                  .row
                    .col-md-3.font-bold= attachment.attachment_type.name
                    .col-md-3= attachment.image_file_name
                    .col-md-3.m-b-md{id: "links-#{attachment.id}"}
                      = link_to attachment.image.url do
                        = image_tag attachment.image.url(:thumb)
                    .col-md-3
                      = button_to attachment_employee_path(@employee, attachment), method: :get, class: "btn btn-primary" do
                        %i.fa.fa-download &nbsp;&nbsp;
                        %span.bold Download
          .clearfix
  .row
    .col-lg-12.m-b-xs
      - if can? :edit, Employee
        = link_to "Edit", edit_employee_path(@employee), class: "btn btn-primary btn-rounded"
      - if can? :index, Employee
        = link_to "All Employees", employees_path, class: "btn btn-primary btn-rounded pull-right"
#blueimp-gallery.blueimp-gallery
  .slides
  %h3.title
  = content_tag 'a', '‹', class: 'prev'
  = content_tag 'a', '›', class: 'next'
  = content_tag 'a', '×', class: 'close'
  = content_tag 'a', nil, class: 'play-pause'
  %ol.indicator