config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords'}
  resources :job_titles, :allowance_types, :vacation_types, :roles, :attachment_types, :roles, :branches, :companies

  resources :currencies do
    collection do
      get 'default'
    end
    member do
      post 'default' => 'currencies#set_default'
    end
  end

  resources :leave_applications, except: [:edit, :update, :destroy] do
    member do
      post 'approve'
      post 'deny'
    end
  end

  resources :departments do
    member do
      get 'job_titles'
    end
  end

  resources :employees do
    collection do
      get 'download_pdf' => 'employees#download_pdf'
    end
    member do
      get 'download_attachment/:attachment_id' => 'employees#download_attachment',
        as: :attachment
    end
  end

  resources :users, only: [:edit, :new, :create, :index, :destroy, :show, :update] do
    member do
      get 'change_password' => 'users#change_password'
      post 'terminate'      => 'users#terminate'
      post 'unterminate'    => 'users#unterminate'
    end
    collection do
      patch 'update_password'
      get   'check_uniqueness'
    end
  end

  resources :notifications, only: [:index] do
    member do
      post 'mark_as_read'
    end
  end

  resources :journal_entry_sessions, only: [:create] do
    resources :journal_entries, only: [:index, :create, :update, :destroy, :show]
  end

  resources :journal_entries, only: [:index] do
    collection do
      get :build_options
    end
  end

  delete 'journal_entry_sessions/:id/close' => 'journal_entry_sessions#close', as: :close_journal_entry_session

  resources :account_main_types, path: "account_headers", only: [:show, :edit, :update, :index] do
    member do
      get 'account_sub_headers'
    end
  end

  resources :accounts do
    collection do
      get 'view'          => 'accounts#view'
      get 'account_tree'  => 'accounts#account_tree'
      get 'balance_sheet' => 'accounts#balance_sheet'
    end
  end

  resources :account_sub_types, path: 'account_sub_headers' do
    member do
      get 'account_lists'
    end
  end

  resources :account_types, path: 'account_lists'
  get 'profile' => 'users#profile'
  patch 'update_profile' => 'users#update_profile'

  resources :dynamic_menus do
    collection do
      get 'to_account_type_ids/:from_account_type_ids' => 'dynamic_menus#to_account_type_ids'
      get 'check_uniqueness_for_name'
    end
    resources :transactions
  end

  get 'shift_summary' => 'transactions#shift_summary'
end

app/models/currency.rb
class Currency < ApplicationRecord
  has_many :allowance_types

  validates :name, :code, :symbol, :country, presence: true
  validates :name, :code, :symbol, uniqueness: true

  scope :default, -> { where(default: true) }

  def self.unset_default
    default_currency = Currency.default.first
    default_currency.update_attribute(:default, false) unless default_currency.blank?
  end

  def default?
    default
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  load_and_authorize_resource
  before_action :set_currency, only: [:edit, :update, :show, :destroy, :set_default]
  helper_method :sort_column

  def new
    @currency = Currency.new
  end

  def create
    @currency = Currency.new(currency_params)
    if @currency.save
      redirect_to @currency, notice: "Currency has successfully been saved."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @currency.update_attributes(currency_params)
      redirect_to @currency, notice: "Currency has successfully been updated."
    else
      render :edit
    end
  end

  def show
  end

  def index
    @currencies = Currency.order(sort_column + " " + sort_direction)
  end

  def destroy
    @currency && @currency.destroy    
    respond_to do |format|
      flash.now[:notice] = "Currency: #{@currency.name} has been deleted." 
      format.js
    end
  end

  def set_default
    Currency.unset_default
    @currency.update_attribute(:default, true)
    render json: { default_currency_name: @currency.name }
  end

  def default
    @currency_names_and_ids = Currency.pluck(:name, :id)
    @default_currency_id    = Currency.default.try(:first).try(:id)
    @default_currency_name  = Currency.default.try(:first).try(:name) || "Not selected yet!"
  end

  private

  def currency_params
    params.require(:currency).permit(:name, :code, :symbol, :country) 
  end

  def set_currency
    @currency = Currency.find(params[:id]) 
  end

  def sort_column
    Currency.column_names.include?(params[:sort])? params[:sort] : "id"
  end
end

app/views/currencies/_form.html.haml
= form_for currency, html: { class: "form-horizontal", id: "manageCurrencies" } do |f|
  = render "shared/errors", resource: currency
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .hr-line-dashed
  .form-group
    = f.label :code, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :code, class: 'form-control'
  .hr-line-dashed
  .form-group
    = f.label :symbol, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :symbol, class: 'form-control'
  .hr-line-dashed
  .form-group
    = f.label :country, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :country, class: 'form-control'
  .form-group
    .col-sm-4.col-sm-offset-2
      = f.submit "Save", class: "btn btn-primary"
      = link_to "Cancel", currencies_path, class: "btn btn-primary"

app/views/currencies/default.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      = link_to "Back", currencies_path, class: "btn btn-primary btn-rounded pull-left m-sm"
      .ibox.float-e-margins
        .ibox-title
          %h2 Choose the default currency
        .ibox-content
          .form-horizontal
            .form-group
              = label_tag nil, "Choose default currency", class: 'col-sm-3 control-label'
              .col-sm-3
                = select_tag :default_currency_id, options_for_select(@currency_names_and_ids, selected: @default_currency_id), class: "form-control", prompt: "Pleaes choose default currency.", id: "currencySelectTag"
              .col-sm-1
                = link_to "Save", "", class: "btn btn-primary", id: "setDefaultCurrency", data: { style: "zoom-in" }
              .col-sm-2.currency-default
                %span.label.label-primary Default Currency
              .col-sm-3.currency-default#defaultCurrencyName
                = @default_currency_name
            %br
            .hr-line-dashed

app/views/currencies/destroy.js.erb
$("[data-id=<%= @currency.id %>]").remove();
$(".wrapper-content").prepend("<%= j render "shared/flash_messages" %>");

app/views/currencies/edit.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :index, Currency
        = link_to "All Currencies", currencies_path, class: "btn btn-primary btn-rounded m-sm"
      .ibox.float-e-margins
        .ibox-title
          %h5 Edit a Currency
        .ibox-content
          = render 'form', currency: @currency

app/views/currencies/index.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :new, Currency
        = link_to "Choose a default currency", default_currencies_path, class: "btn btn-primary btn-rounded pull-right m-sm"
        = link_to new_currency_path, class: "btn btn-primary btn-rounded m-sm pull-right" do
          %i.fa.fa-plus{"aria-hidden" => true}
          &nbsp;&nbsp; New Currency
      .ibox.float-e-margins
        .ibox-title All Currencies
        .ibox-content
          .table-responsive
            %table.table.table-bordered.table-striped.pretty
              %thead
                %tr
                  - if can? :show, Currency
                    %th= sortable "id", "#"
                  %th= sortable "name"
                  %th= sortable "code"
                  %th= sortable "symbol"
                  %th= sortable "country"
                  %th Default
                  - if can?(:edit, Currency) || can?(:destroy, Currency)
                    %th Actions
              %tbody
                - @currencies.each do |currency|
                  %tr{data: { id: currency.id } }
                    - if can? :show, Currency
                      %td= link_to currency.id, currency
                    %td= currency.name
                    %td= currency.code
                    %td= currency.symbol
                    %td= currency.country
                    %td
                      - if currency.default?
                        %i.fa.fa-check{"aria-hidden" => true}
                      - else
                        %i.fa.fa-times{"aria-hidden" => true}
                    - if can?(:edit, Currency) || can?(:destroy, Currency)
                      %td
                        - if can?(:destroy, Currency)
                          = link_to currency, method: :delete, remote: true, data: { confirm: "Are you sure to delete this currency from database?" }, class: "action-link" do
                            %i.fa.fa-trash{"aria-hidden" => true}
                        - if can?(:edit, Currency)
                          = link_to edit_currency_path(currency), class: "action-link" do
                            %i.fa.fa-pencil{"aria-hidden" => true}

app/views/currencies/new.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :index, Currency
        = link_to "All Currencies", currencies_path, class: "btn btn-primary btn-rounded m-sm"
      .ibox.float-e-margins
        .ibox-title
          %h5 Create a new Currency
        .ibox-content
          = render 'form', currency: @currency

app/views/currencies/show.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-title
          %h2=@currency.name
        .ibox-content
          .col-md-2
            %p.font-bold Name
          .col-md-10
            %p= @currency.name
          %br
          .col-md-2
            %p.font-bold Code
          .col-md-10
            %p= @currency.code
          %br
          .col-md-2
            %p.font-bold Symbol
          .col-md-10
            %p= @currency.symbol
          %br
          .col-md-2
            %p.font-bold Country
          .col-md-10
            %p= @currency.country
          %br
          .clearfix
  .row
    .col-lg-12
      - if can? :edit, Currency
        = link_to "Edit", edit_currency_path(@currency), class: "btn btn-primary btn-rounded"
      - if can? :index, Currency
        = link_to "All Currencies", currencies_path, class: "btn btn-primary btn-rounded"