config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords'}
  resources :job_titles, :allowance_types, :vacation_types, :roles, :attachment_types, :roles, :branches, :companies

  resources :currencies do
    collection do
      get 'default'
    end
    member do
      post 'default' => 'currencies#set_default'
    end
  end

  resources :leave_applications, except: [:edit, :update, :destroy] do
    member do
      post 'approve'
      post 'deny'
    end
  end

  resources :departments do
    member do
      get 'job_titles'
    end
  end

  resources :employees do
    collection do
      get 'download_pdf' => 'employees#download_pdf'
    end
    member do
      get 'download_attachment/:attachment_id' => 'employees#download_attachment',
        as: :attachment
    end
  end

  resources :users, only: [:edit, :new, :create, :index, :destroy, :show, :update] do
    member do
      get 'change_password' => 'users#change_password'
      post 'terminate'      => 'users#terminate'
      post 'unterminate'    => 'users#unterminate'
    end
    collection do
      patch 'update_password'
      get   'check_uniqueness'
    end
  end

  resources :notifications, only: [:index] do
    member do
      post 'mark_as_read'
    end
  end

  resources :journal_entry_sessions, only: [:create] do
    resources :journal_entries, only: [:index, :create, :update, :destroy, :show]
  end

  resources :journal_entries, only: [:index] do
    collection do
      get :build_options
    end
  end

  delete 'journal_entry_sessions/:id/close' => 'journal_entry_sessions#close', as: :close_journal_entry_session

  resources :account_main_types, path: "account_headers", only: [:show, :edit, :update, :index] do
    member do
      get 'account_sub_headers'
    end
  end

  resources :accounts do
    collection do
      get 'view'          => 'accounts#view'
      get 'account_tree'  => 'accounts#account_tree'
      get 'balance_sheet' => 'accounts#balance_sheet'
    end
  end

  resources :account_sub_types, path: 'account_sub_headers' do
    member do
      get 'account_lists'
    end
  end

  resources :account_types, path: 'account_lists'
  get 'profile' => 'users#profile'
  patch 'update_profile' => 'users#update_profile'

  resources :dynamic_menus do
    collection do
      get 'to_account_type_ids/:from_account_type_ids' => 'dynamic_menus#to_account_type_ids'
      get 'check_uniqueness_for_name'
    end
    resources :transactions
  end

  get 'shift_summary' => 'transactions#shift_summary'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  load_and_authorize_resource

  before_action :set_dynamic_menu, only: [:new, :create, :edit, :update, :show, :destroy, :index]
  before_action :set_transaction, only: [:create, :edit, :update, :show, :destroy]

  def new
    @transaction = @dynamic_menu.transactions.new
    @transaction.attachments.build
  end

  def create
    @transaction = @dynamic_menu.transactions.build(transaction_params)
    @transaction.user = current_user
    if @transaction.save
      redirect_to [@dynamic_menu, @transaction], notice: "Transaction has successfully been saved."
    else
      render :new
    end
  end

  def edit
    @transaction.attachments.build
  end

  def update
    @transaction.user = current_user
    if @transaction.update_attributes(transaction_params)
      respond_to do |format|
        format.html { redirect_to [@dynamic_menu, @transaction], notice: "Transaction has successfully been updated."
 }
        format.js { flash.now[:notice] = "Transaction has successfully been updated."  }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.js
      end
    end
  end

  def show
  end

  def index
    @transactions = @dynamic_menu.transactions
  end

  def destroy
    @transaction && @transaction.destroy
    respond_to do |format|
      flash.now[:notice] = "Transaction: #{@transaction.name} has been deleted."
      format.js
    end
  end

  def shift_summary
    date = params[:date_for_transaction] || Date.today
    @transactions = Transaction.where(happened_at: date)
  end

  private

  def transaction_params
    params.require(:transaction).permit(:from_account_id, :to_account_id, :amount, :happened_at, :description, attachments_attributes: [:id, :image, :_destroy])
  end

  def set_dynamic_menu
    @dynamic_menu = DynamicMenu.find(params[:dynamic_menu_id])
  end

  def set_transaction
    @transaction = @dynamic_menu.transactions.find_by(transactions: { id: params[:id]  })
  end
end

app/views/transactions/_attachment.html.haml
.row.form-inline.transaction-attachment
  - if f.object.image?
    .fileinput.fileinput-exists{ data: { provides: "fileinput" } }
      %span.btn.btn-default.btn-file
        %span.fileinput-new Select File
        %span.fileinput-exists Change
        = f.file_field :image, class: 'form-control'
      %span.fileinput-filename= f.object.image_file_name
    = image_tag f.object.image.url(:thumb), class: 'm-l-sm'
  - else
    .fileinput.fileinput-new{ data: { provides: "fileinput" } }
      %span.btn.btn-default.btn-file
        %span.fileinput-new Select File
        %span.fileinput-exists Change
        = f.file_field :image, class: 'form-control'
      %span.fileinput-filename
  = f.link_to_remove 'Remove', class: 'btn btn-outline btn-danger btn-xs m-l-sm'

app/views/transactions/_form.html.haml
= nested_form_for [dynamic_menu, transaction], html: { class: "form-horizontal", id: "manageTransactions" } do |f|
  = render "shared/errors", resource: transaction
  .form-group
    = f.label :happened_at, 'Date', class: 'col-sm-2 control-label'
    .col-sm-2.input-group.date.m-r-md
      %span.input-group-addon
        %i.fa.fa-calendar
      = f.text_field :happened_at, class: 'form-control input-group date', id: "transactionHappenedAt"
  .hr-line-dashed
  .form-group
    = f.label :amount, class: 'col-sm-2 control-label'
    .col-sm-2.transaction-amount-field
      = f.number_field :amount, class: 'form-control', step: 'any'
  .hr-line-dashed
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, class: 'form-control'
  .hr-line-dashed
  .form-group
    = f.label :from_account_id, "From", class: "col-sm-2 control-label"
    .col-sm-10
      = f.select :from_account_id,  grouped_options_for_select(dynamic_menu.from_account_types.includes(:accounts).map { |account_type| [account_type.name, account_type.accounts.pluck(:name, :id)] }), { prompt: "Select an account" }, class: "form-control"
  .hr-line-dashed
  .form-group
    = f.label :to_account_id, "To", class: "col-sm-2 control-label"
    .col-sm-10
      = f.select :to_account_id,  grouped_options_for_select(dynamic_menu.to_account_types.includes(:accounts).map { |account_type| [account_type.name, account_type.accounts.pluck(:name, :id)] }), { prompt: "Select an account" }, class: "form-control"
  .hr-line-dashed
  .form-group
    = label_tag :attachments, "Attachments", class: 'col-sm-2 control-label'
    .col-sm-10
      = f.fields_for :attachments do |attachment_field|
        = render 'attachment', f: attachment_field
      = f.link_to_add :attachments, class: 'btn btn-primary m-t-xs' do
        %i.fa.fa-plus-circle
        %span.bold Add a new attachment
  .hr-line-dashed
  .form-group
    .col-sm-4.col-sm-offset-2
      = f.submit "Save", class: "btn btn-primary"
      = link_to "Cancel", account_types_path, class: "btn btn-primary"

app/views/transactions/_transaction.html.haml
%tr.animated.fadeInDown{data: { id: transaction.id } }
  %td.font-bold= link_to transaction.id, [dynamic_menu, transaction]
  %td= transaction.from_account.try(:name)
  %td= transaction.to_account.try(:name)
  %td= transaction.amount
  %td= transaction.happened_at.strftime("%b %d, %Y")
  %td= link_to dynamic_menu.name, dynamic_menu
  %td= transaction.description
  - if can? :edit, Transaction
    %td
      = link_to "#", class: "action-link", data: { toggle: "modal", target: "#transactionModal#{transaction.id}" } do
        %i.fa.fa-pencil{"aria-hidden" => true}

app/views/transactions/_transaction_form.html.haml
.modal.inmodal.fade{tabindex: "-1", role: "dialog", "aria-hidden" => "true", id: "transactionModal#{transaction.id}"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: "button", data: { dismiss: "modal" }}
          %span{"aria-hidden" => "true"} &times;
          %span.sr-only Close
        %h4 Update the Transaction
      .modal-body
        = nested_form_for [dynamic_menu, transaction], html: { class: "form-horizontal", id: "updateTransaction#{transaction.id}" } do |f|
          = render "shared/errors", resource: transaction
          .form-group
            = f.label :happened_at, 'Date', class: 'col-sm-2 control-label'
            .col-sm-4.input-group.date.m-r-md
              %span.input-group-addon
                %i.fa.fa-calendar
              = f.text_field :happened_at, class: 'form-control input-group date', id: "transactionHappenedAt", required: true
          .hr-line-dashed
          .form-group
            = f.label :amount, class: 'col-sm-2 control-label'
            .col-sm-4.transaction-amount-field
              = f.number_field :amount, class: 'form-control', step: 'any', required: true
          .hr-line-dashed
          .form-group
            = f.label :description, class: 'col-sm-2 control-label'
            .col-sm-10
              = f.text_area :description, class: 'form-control'
          .hr-line-dashed
          .form-group
            = f.label :from_account_id, "From", class: "col-sm-2 control-label"
            .col-sm-10
              = f.select :from_account_id,  grouped_options_for_select(dynamic_menu.from_account_types.includes(:accounts).map { |account_type| [account_type.name, account_type.accounts.pluck(:name, :id)] }), { prompt: "Select an account" }, class: "form-control", required: true
          .hr-line-dashed
          .form-group
            = f.label :to_account_id, "To", class: "col-sm-2 control-label"
            .col-sm-10
              = f.select :to_account_id,  grouped_options_for_select(dynamic_menu.to_account_types.includes(:accounts).map { |account_type| [account_type.name, account_type.accounts.pluck(:name, :id)] }), { prompt: "Select an account" }, class: "form-control", required: true
          .hr-line-dashed
          .form-group
            = label_tag :attachments, "Attachments", class: 'col-sm-2 control-label'
            .col-sm-10
              = f.fields_for :attachments do |attachment_field|
                = render 'attachment', f: attachment_field
              = f.link_to_add :attachments, class: 'btn btn-primary m-t-xs' do
                %i.fa.fa-plus-circle
                %span.bold Add a new attachment
          .hr-line-dashed
          .form-group
            .col-sm-4.col-sm-offset-2
              = link_to "Update", "#", class: "btn btn-primary update-transaction", data: { style: "zoom-in", dynamic_menu_id: transaction.dynamic_menu_id, transaction_id: transaction.id }
              = link_to "Close", accounts_path, class: "btn btn-white", data: { dismiss: "modal" }

app/views/transactions/destroy.js.erb
$("[data-id=<%= @transaction.id %>]").remove();
$(".wrapper-content").prepend("<%= j render "shared/flash_messages" %>");

app/views/transactions/edit.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :index, Transaction
        = link_to "See all the transactions in #{@dynamic_menu.name}", dynamic_menu_transactions_path(@dynamic_menu), class: "btn btn-primary btn-rounded m-sm"
      .ibox.float-e-margins
        .ibox-title
          %h5= "Edit the transaction in #{@dynamic_menu.name}"
        .ibox-content
          = render 'form', dynamic_menu: @dynamic_menu, transaction: @transaction

app/views/transactions/index.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :new, Transaction
        = link_to new_dynamic_menu_transaction_path(@dynamic_menu), class: "btn btn-primary btn-rounded m-sm pull-right" do
          %i.fa.fa-plus{"aria-hidden" => true}
          &nbsp;&nbsp;
          = "New Transaction in #{@dynamic_menu.name}"
      .ibox.float-e-margins
        .ibox-title= "All Transactions in #{@dynamic_menu.name}"
        .ibox-content
          .table-responsive
            %table.table.table-bordered.table-striped
              %thead
                %tr
                  - if can? :show, Transaction
                    %th ID
                  %th Entered By
                  %th Description
                  %th From Account
                  %th To Account
                  %th Amount
                  %th Date
                  - if can?(:edit, Transaction) || can?(:destroy, Transaction)
                    %th Actions
              %tbody
                - @transactions.each do |transaction|
                  %tr{data: { id: transaction.id } }
                    - if can? :show, Transaction
                      %td.font-bold= link_to transaction.id, [@dynamic_menu, transaction]
                    %td= transaction.user.try(:full_name)
                    %td= truncate(transaction.description)
                    %td
                      %span.label.label-primary= transaction.from_account.try(:name)
                    %td
                      %span.label.label-primary= transaction.to_account.try(:name)
                    %td= transaction.amount.to_s
                    %td= transaction.happened_at.strftime("%b %d, %Y")
                    - if can?(:edit, Transaction) || can?(:destroy, Transaction)
                      %td
                        - if can? :delete, Transaction
                          = link_to [@dynamic_menu, transaction], method: :delete, remote: true, data: { confirm: "Are you sure to delete this transaction from database?" }, class: "action-link" do
                            %i.fa.fa-trash{"aria-hidden" => true}
                        - if can? :edit, Transaction
                          = link_to edit_dynamic_menu_transaction_path(@dynamic_menu, transaction), class: "action-link" do
                            %i.fa.fa-pencil{"aria-hidden" => true}

app/views/transactions/new.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      - if can? :index, Transaction
        = link_to "See all the transactions in #{@dynamic_menu.name}", dynamic_menu_transactions_path(@dynamic_menu), class: "btn btn-primary btn-rounded m-sm"
      .ibox.float-e-margins
        .ibox-title
          %h5= "Create a transaction in #{@dynamic_menu.name}"
        .ibox-content
          = render 'form', dynamic_menu: @dynamic_menu, transaction: @transaction

app/views/transactions/shift_summary.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-title.p-sm
          .col-sm-4.pull-right
            .form-group.m-t-n-xs-for-shif-summary
              .input-group.date
                %span.input-group-addon
                  %i.fa.fa-calendar
                = text_field_tag :date_for_transaction, nil, class: 'form-control input-group date', id: "dateForTransactions"
          .font-bold
            = "Shift Summary" + (params[:date_for_transaction].present? ? " for #{Date.parse(params[:date_for_transaction]).strftime('%b %d, %Y')}" : '')
            .text-info
        .ibox-content
          .table-responsive
            %table.table.table-bordered.table-striped
              %thead
                %tr
                  - if can? :show, Transaction
                    %th ID
                  %th From Account
                  %th To Account
                  %th Amount
                  %th Created Through
                  %th Description
                  - if can?(:edit, AccountMainType)
                    %th Actions
              %tbody
                - @transactions.each do |transaction|
                  %tr{data: {id: transaction.id}}
                    - if can? :show, Transaction
                      %td.font-bold= link_to transaction.id, [transaction.dynamic_menu, transaction]
                    %td= transaction.from_account.try(:name)
                    %td= transaction.to_account.try(:name)
                    %td= transaction.amount
                    %td= link_to transaction.dynamic_menu.try(:name), transaction.dynamic_menu
                    %td= transaction.description
                    - if can?(:edit, Transaction)
                      %td
                        - if can? :edit, AccountMainType
                          = link_to "#", class: "action-link", data: { toggle: "modal", target: "#transactionModal#{transaction.id}" } do
                            %i.fa.fa-pencil{"aria-hidden" => true}
#transactionFormModals
  - @transactions.each do |transaction|
    = render 'transaction_form', dynamic_menu: transaction.dynamic_menu, transaction: transaction

app/views/transactions/show.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-title
          %h2= "Transaction in #{@dynamic_menu.name}"
        .ibox-content
          .row
            .col-md-2
              %p.font-bold Entered By
            .col-md-10
              %p= @transaction.user.try(:full_name)
          .row
            .col-md-2
              %p.font-bold Description
            .col-md-10
              %p= @transaction.description
          .row
            .col-md-2
              %p.font-bold From Account
            .col-md-10
              %p
                %span.label.label-primary= @transaction.from_account.name
          .row
            .col-md-2
              %p.font-bold To Account
            .col-md-10
              %p
                %span.label.label-primary= @transaction.to_account.name
          .row
            .col-md-2
              %p.font-bold Amount
            .col-md-10
              %p= @transaction.amount
          .row
            .col-md-2
              %p.font-bold Date
            .col-md-10
              %p= @transaction.happened_at.strftime("%b %d, %Y")
          .row
            .col-md-2
              %p.font-bold Attachments
            .col-md-10
              - @transaction.attachments.each do |attachment|
                = image_tag attachment.image.url(:thumb), class: "m-r-sm"
          .clearfix
  .row
    .col-lg-12
      - if can? :edit, Transaction
        = link_to "Edit", edit_dynamic_menu_transaction_path(@dynamic_menu, @transaction), class: "btn btn-primary btn-rounded"
      - if can? :index, Transaction
        = link_to "All Transactions in #{@dynamic_menu.name}", dynamic_menu_transactions_path, class: "btn btn-primary btn-rounded"

app/views/transactions/update.js.erb
<% if @transaction.valid? %>
  $("tr[data-id=<%= @transaction.id %>]").replaceWith("<%= j render "transactions/transaction", dynamic_menu: @dynamic_menu, transaction: @transaction %>");
  $("#transactionModal<%= @transaction.id %>").modal('hide');
  $(".wrapper-content").prepend("<%= j render "shared/flash_messages" %>");
<% else %>
  $("#updateTransaction<%= @transaction.id %>").prepend("<%= j render "shared/errors", resource: @transaction %>");
<% end %>